version: '3.8'
services:
  kanjiou-api:
    build: api
    container_name: kanjiou-api
    tty: true
    volumes:
      - ./api:/var/www/html
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - kanjiou-db
  kanjiou-nginx:
    image: nginx:1.21
    container_name: kanjiou-nginx
    ports:
      - 8080:8080
    volumes:
      - ./api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - kanjiou-api
  kanjiou-db:
    image: mysql:5.7
    container_name: kanjiou-db
    volumes:
        - ./mysql_lib:/var/lib/mysql
        - ./mysql_conf:/etc/mysql/conf.d
        - ./mysql/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"