name: wakeup databaseeeeee plzzzzzzzzzzz
 
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  hello_job:
    runs-on: ubuntu-18.04
    steps:
      - run: curl -X GET https://kanjiouapi.onrender.com/api/ranks
